### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by nournia** [adsva/python-wapiti#16]
Hi,
I've tried to build this package in Windows, and there is some errors which you may want to fix:

    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Icwapiti/src -Ilibwapiti -IC:\Python34\include -IC:\Python34\include /Tccwapiti/src/bcd.c /Fobuild\temp.win32-3.4\Release\cwapiti/src/bcd.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99' 
    bcd.c
    cwapiti/src/bcd.c(30) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory

[Here](https://ci.appveyor.com/project/nournia/python-wapiti) is complete build log for common python versions and windows architectures.

**Comment by adsva** [comment]
Hi,

I don't have a windows machine available right now to test this, but it looks like in order to compile c-programs written in C99, you might need to install visual studio 2013:

http://blogs.msdn.com/b/vcblog/archive/2013/07/19/c99-library-support-in-visual-studio-2013.aspx

Thanks for reporting, I'll add a note in the readme to help people building on windows!

**Comment by mohsenrbb** [comment]
Hi,
I'm using visual studio 2013, according to this [answer](http://stackoverflow.com/a/70630) my cl output is:
```
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.30723 for x86 ....
```
But when I want to compile this package in windows I got this error:
```
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Icwapiti/src -Ilibwapiti -IC:\Python34\include -IC:\Python34\include /Tccwapiti/src/bcd.c /Fobuild\temp.win32-3.4\Release\cwapiti/src/bcd.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    bcd.c
    c:\users\m-r\appdata\local\temp\pip-build-rbuqyz8g\libwapiti\cwapiti\src\model.h(33) : fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\BIN\\cl.exe' failed with exit status 2
```
After that I've been Googled this and I can only find this [answer](http://stackoverflow.com/a/15177658)
Is this correct? or It is a compiling issue?

**Comment by adsva** [comment]
I see. Well, it looks like the underlying wapiti library isn't windows compatible. I'll take a closer look, but like I said before I don't have a windows machine on hand to test this, so it probably won't be a quick fix. If you figure it out yourself, I suggest you submit a pull request to the wapiti repository that I am including as a submodule.

**Comment by mohsenrbb** [comment]
I installed wapiti successfully using cygwin and gcc.
but when I want to use your package again I got error
```
>>> from wapiti import model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.2/site-packages/wapiti/__init__.py", line 1, in <module>
    from .api import *
  File "/usr/lib/python3.2/site-packages/wapiti/api.py", line 28, in <module>
    os.listdir(_libwapiti_root_path)
IndexError: pop from empty list
```
what is this error cause?

**Comment by adsva** [comment]
Could you try printing _libwapiti_root_path before that line and checking if there's anything in that directory? Either the build isn't working at all and there's no file, or the root path is wrong, or there's another type of file in the directory. Not sure what you'll get when building under cygwin.
